// Generated by scripts/types.ts from packages/domain/v1/openapi.snapshot.json. Do not edit.
// The person API 2026-10-05: what /v1 sends (outputs) and reads (requests and queries).

export const API_VERSION = "2026-10-05"

export type Me = {
  user: {
    id: string
  }
  workspace: {
    id: string
  }
  app: {
    id: string
    name: string
    verified: boolean
  }
  grant: {
    id: string
    scopes: ("cards:read" | "cards:read:all" | "cards:answer" | "cards:reply" | "cards:later" | "cards:delegate" | "assistants:read" | "presence:desk")[]
    reach: "machine" | "all"
    machine?: {
      id: string
      name: string
    }
    dpop: boolean
    createdAt: string
    expiresAt: string
  }
}

export type Card = {
  id: string
  version: number
  status: "pending" | "delegated" | "answered" | "resolved" | "snoozed" | "expired" | "cancelled"
  turn: "you" | "agent"
  kind: "choice" | "multi" | "approve" | "text" | "review" | "action" | "fyi" | "group"
  intent?: "decide" | "approve" | "do" | "tell" | "heads_up"
  title: string
  summary: string
  urgency: "now" | "today" | "whenever"
  blocking: boolean
  fallback?: {
    text: string
    at: string
  }
  options?: {
    id: string
    label: string
    detail?: string
    consequence?: string
    sends?: {
      to: string
    }
  }[]
  recommendedIds?: string[]
  rationale?: string
  multi?: {
    min: number
    max: number
  }
  approve?: {
    action: string
    command?: string
    risk: "low" | "medium" | "high"
    reversible: boolean
    because?: "spends" | "irreversible" | "public"
  }
  text?: {
    placeholder: string
    suggestions?: string[]
    long?: boolean
  }
  action?: {
    where?: string
    steps: (string | {
      text: string
      command?: string
    })[]
    done?: string
    command?: string
    verify?: string
  }
  questions?: {
    id: string
    kind: "choice" | "multi" | "approve" | "text"
    title: string
    detail?: string
    options?: {
      id: string
      label: string
      detail?: string
      consequence?: string
      sends?: {
        to: string
      }
    }[]
    recommendedIds?: string[]
    rationale?: string
    multi?: {
      min: number
      max: number
    }
    approve?: {
      action: string
      command?: string
      risk: "low" | "medium" | "high"
      reversible: boolean
      because?: "spends" | "irreversible" | "public"
    }
    highStakes?: boolean
    text?: {
      placeholder: string
      suggestions?: string[]
      long?: boolean
    }
  }[]
  about?: {
    kind: "email" | "pr" | "booking" | "document" | "other"
    title: string
    ref?: string
  }
  threadId?: string
  follows?: string
  highStakes: boolean
  actions: ("answer" | "undo" | "reply" | "later" | "back" | "delegate" | "take_back")[]
  area: {
    id: string
    name: string
  }
  asker: {
    assistant: {
      id: string
      name: string
      app: "claude-code" | "codex" | "cursor" | "gemini-cli" | "opencode" | "pi" | "grok" | "muse" | "chatgpt" | "claude" | "dots" | "other" | "webhook"
      appName: string
    }
    agent?: {
      id: string
      name: string
    }
    task: {
      label: string
      cwd?: string
      branch?: string
    }
    machine?: {
      id?: string
      name: string
    }
  }
  askedFirst?: {
    where: "terminal" | "chat"
    at: string
    why?: "quiet" | "away"
  }
  answer?: Answer
  undoUntil?: string
  snoozedUntil?: string
  delegation?: {
    to: {
      assistantId: string
      agentId?: string
    }
    mode: "freely" | "loop"
    state: "working" | "suggested" | "answered" | "returned" | "taken_back"
    at: string
  }
  ask?: {
    id: string
    from: "helper" | "asker"
    name: string
    title: string
    summary?: string
    options?: {
      id: string
      label: string
      detail?: string
      consequence?: string
      sends?: {
        to: string
      }
    }[]
    recommendedIds?: string[]
    rationale?: string
    highStakes: boolean
    at: string
    answered?: {
      choiceIds?: string[]
      text?: string
      note?: string
      answeredAt: string
    }
  }
  context?: {
    background: string
    trace: {
      state: "done" | "paused" | "warn" | "failed"
      text: string
    }[]
    filesTouched: string[]
    tried: string[]
    links: {
      label: string
      url: string
    }[]
  }
  artifacts?: {
    kind: "image" | "diff" | "url" | "file" | "draft" | "code"
    title: string
    ref: string
    attachmentId?: string
    /** image or file: true for an uploadUrl */
    upload?: boolean
    lines?: string[]
    caption?: string
    lang?: "ts" | "json" | "shell" | "sql" | "yaml" | "toml" | "css" | "markdown" | "text"
    startLine?: number
  } | {
    kind: "path"
    title: string
    path: string
    machine?: string
    bytes?: number
    modifiedAt?: string
    note?: string
    fetch?: string
  }[]
  attachments?: Attachment[]
  hasFiles?: true
  thread?: {
    id: string
    author: "you" | "agent" | "pendingyou" | "helper" | "teammate"
    teammate?: {
      name: string
    }
    body: string
    via?: "voice" | "text"
    audioSeconds?: number
    attachmentIds?: string[]
    app?: {
      id: string
      name: string
      machine?: string
    }
    createdAt: string
  }[]
  threadCount: number
  partial?: true
  url: string
  createdAt: string
  updatedAt: string
}

export type Answer = {
  answers?: {
    [key: string]: {
      choiceIds?: string[]
      approved?: boolean
      text?: string
      note?: {
        text: string
        via: "voice" | "text"
        audioSeconds?: number
      }
      theyDecide?: boolean
    }
  }
  choiceIds?: string[]
  approved?: boolean
  text?: string
  note?: {
    text: string
    via: "voice" | "text"
    audioSeconds?: number
  }
  theyDecide?: boolean
  failedStep?: number
  by?: "you" | "go-between" | "helper" | "teammate"
  helper?: {
    name: string
    why: string
    note?: string
  }
  where?: "app" | "conversation"
  app?: {
    id: string
    name: string
    machine?: string
  }
  answeredAt: string
}

export type Attachment = {
  id: string
  place: "card" | "message" | "answer"
  title: string
  contentType?: string
  bytes?: number
  downloadUrl?: string
  downloadExpiresAt?: string
}

export type CardList = {
  cards: Card[]
  counts: {
    pending: number
    waiting: number
    later: number
    delegated: number
    elsewhere?: number
  }
  next?: string
}

export type CardResponse = {
  card: Card
}

export type AnswerResponse = {
  id: string
  askId?: string
  status: "answered"
  version: number
  undoUntil: string
}

export type CardBack = {
  id: string
  status: "pending"
  version: number
}

export type MessageResponse = {
  id: string
  messageId: string
  turn: "agent"
  version: number
}

export type LaterResponse = {
  id: string
  status: "snoozed"
  until: string
  version: number
}

export type DelegateResponse = {
  id: string
  status: "delegated"
  version: number
  hears?: "instant" | "every-15-min" | "hourly" | "while-working" | "by-hand"
  undoUntil: string
}

export type ChangeList = {
  changes: Change[]
  cursor: string
  more: boolean
}

export type Change = {
  type: "card.created" | "card.answered" | "card.changed" | "card.closed"
  cardId: string
  at: string
}

export type AssistantList = {
  assistants: Assistant[]
}

export type Assistant = {
  id: string
  app: "claude-code" | "codex" | "cursor" | "gemini-cli" | "opencode" | "pi" | "grok" | "muse" | "chatgpt" | "claude" | "dots" | "other" | "webhook"
  appName: string
  name: string
  machine?: {
    id: string
    name: string
  }
  hears?: "instant" | "every-15-min" | "hourly" | "while-working" | "by-hand"
  agents: {
    id: string
    name: string
    about?: string
    state: "live" | "recent" | "quiet"
    liveAt?: string
    closedAt?: string
    openCards: number
    liveSessions: {
      appSessionId: string
      cwd?: string
      areaId?: string
      liveAt: string
      terminal?: {
        app: "herdr"
        paneId: string
        server?: string
      }
    }[]
  }[]
}

export type Problem = {
  type: string
  title: string
  status: number
  code: "invalid" | "app_not_available" | "high_stakes" | "area_change" | "not_your_answer" | "forbidden" | "not_found" | "method_not_allowed" | "version_conflict" | "not_waiting" | "hold_over" | "delegated" | "conflict" | "idempotency_in_progress" | "idempotency_mismatch" | "rate_limited" | "server_error" | "not_available" | "unavailable"
  detail: string
  requestId?: string
  fields?: string[]
  reason?: string
  why?: "disabled" | "unverified" | "not_registered" | "off"
  url?: string
  currentVersion?: number
  cardStatus?: "pending" | "delegated" | "answered" | "resolved" | "snoozed" | "expired" | "cancelled"
  retryAfterSeconds?: number
  scope?: "read" | "write" | "answers" | "wait" | "workspace"
}

export type ListCardsQuery = {
  status?: "pending" | "snoozed" | "delegated" | "done"
  area?: string[]
  assistant?: string[]
  agent?: string[]
  app?: ("claude-code" | "codex" | "cursor" | "gemini-cli" | "opencode" | "pi" | "grok" | "muse" | "chatgpt" | "claude" | "dots" | "other" | "webhook")[]
  machine?: string[]
  threadId?: string
  limit?: number
  whole?: number
  after?: string
}

export type AnswerRequest = {
  version: number
  choiceIds?: string[]
  approved?: boolean
  text?: string
  note?: {
    text: string
    via?: "text" | "voice"
  }
  theyDecide?: true
  answers?: {
    [key: string]: {
      choiceIds?: string[]
      approved?: boolean
      text?: string
      note?: {
        text: string
        via: "voice" | "text"
        audioSeconds?: number
      }
      theyDecide?: boolean
    }
  }
  failedStep?: number
  askId?: string
}

export type UndoRequest = Record<string, never>

export type MessageRequest = {
  body: string
  via?: "text" | "voice"
}

export type LaterRequest = {
  /** A time, or a preset: in an hour, tonight (6:00 PM) or tomorrow morning (8:00 AM), in timeZone. */
  until: string | ("1h" | "tonight" | "tomorrow")
  /** The person’s IANA time zone, e.g. "America/Chicago", for the presets. Default UTC. */
  timeZone?: string
}

export type BackRequest = Record<string, never>

export type DelegateRequest = {
  to: {
    assistantId: string
    agentId?: string
  }
  mode: "freely" | "loop"
  note?: string
}

export type TakeBackRequest = Record<string, never>

export type ChangesQuery = {
  after?: string
  wait?: number
  limit?: number
}

export type PresenceRequest = {
  here: boolean
}
